name: End2End MLOps with HugginFace

on:
  # Triggers the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # Allow to run workflow manually from Actions tab
  workflow_dispatch:
  
jobs:
  
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://hausdorff94:$HF@huggingface.co/spaces/hausdorff94/e2e-MLops-GH-Actions
      - name: Push to hub
        env:
          HF: ${{ secrects.HF }}
        run: git push --force https://hausdorff94:$HF@huggingface.co/spaces/hausdorff94/e2e-MLops-GH-Actions main
